### PR TITLE
single impl created

### PR DESCRIPTION
**Pull request by gilescope**
Cargo test runs cleanly now (no tests yet)
proc macro now adds items to existing impl rather than generating another with same name.

(heading towards making Vec args work)

### CODE REVIEW

**Comment by spacekookie** [comment]
The fact that `thunder` creates a new `impl` block was *kinda* by design, not an oversight. It makes debugging generated code a lot easier because you can grep for the special comment above the impl block.

What else exactly are you trying to solve with this PR?

**Comment by gilescope** [comment]
Other than that, just making cargo test run cleanly. At the moment it tries to run some of the docs that isn't code leading to odd error messages.

**Comment by gilescope** [comment]
Ok, so these are the cargo test changes. Might be easier to just do these on your local branch (or alternatively I can create a clean pull request with those changes in).

**Comment by spacekookie** [comment]
Yea, this is okay, I'm gonna squash it down anyways :)

Thanks for the contribution

**Pull request merged**
