### PR TITLE
Fix #15

### LINKED ISSUE #15: Commas in global options causes compile error
A minimal reproducible code can be found here, along with the compile erro, in comma_error.rs file: https://gist.github.com/gugahoa/25b79588ab566360ef586e57cbef993d

### PR DESCRIPTION
**Pull request by gugahoa**
Made some changes to how global argument options are parsed, without adding new dependencies.
A friend of mine gave this idea, and made a Go program to showcase, which I think is easier to understand: https://play.golang.org/p/QummfD0ARMK

### CODE REVIEW

**Comment by spacekookie** [comment]
Thanks for this :+1:

**Comment by gugahoa** [comment]
There's a conflict because of the experimentation with the DSL, how should I go about this? Solve the conflict while also maintaining the new DSL?

**Comment by spacekookie** [comment]
Yea, I saw that. I've been playing around with it a little. Hmm…tbh, I would be inclined to just merge it for now, then adjust the code bit by bit to support the new DSL.

If you want to give refactoring it a shot, go ahead. But I'd be happy to merge the change just as it is now.

**Comment by gugahoa** [comment]
I believe that for now it's good to merge, I went ahead and solved the merge conflict.

**Comment by spacekookie** [comment]
Thanks for the work :slightly_smiling_face:

**Pull request merged**
